// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function GetSnippetPaths() {
  return window['go']['main']['App']['GetSnippetPaths']();
}

export function Move(arg1, arg2) {
  return window['go']['main']['App']['Move'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function UpdateFile(arg1, arg2) {
  return window['go']['main']['App']['UpdateFile'](arg1, arg2);
}
